import Fashion from '../assets/images/category/Fashion1.png';
import Grocery from '../assets/images/category/Grocery.png';
import Electronics from '../assets/images/category/Electronics3.png';
import Food from '../assets/images/category/Food.png';
import Home from '../assets/images/category/Home1.png';
import Health from '../assets/images/category/Health1.png';
import BPC from '../assets/images/category/BPC.png';

export const categoryList = [
    {id: '1', name: 'Fashion', shortName: 'Fashion', imageUrl: Fashion, routeName: 'Fashion'},
    {id: '2', name: 'Grocery', shortName: 'Grocery', imageUrl: Grocery, routeName: 'Grocery'},
    {id: '3', name: 'Electronics', shortName: 'Electronics', imageUrl: Electronics, routeName: 'Electronics'},
    {id: '4', name: 'Food & Beverage', shortName: 'F&B', imageUrl: Food, routeName: 'F&B'},
    {id: '5', name: 'Home & Decor', shortName: 'Home & Decor', imageUrl: Home, routeName: 'Home & Decor'},
    {id: '6', name: 'Health & Wellness', shortName: 'Health & Wellness', imageUrl: Health, routeName: 'Health & Wellness'},
    {id: '7', name: 'Beauty & Personal Care', shortName: 'BPC', imageUrl: BPC, routeName: 'BPC'},
];

export const PRODUCT_SUBCATEGORY = {
    "Grocery": [
        {value: 'Fruits and Vegetables', key: 'Fruits and Vegetables', protocolKey: "@ondc/org/mandatory_reqs_veggies_fruits", imageUrl: Grocery},
        {value: 'Masala & Seasoning', key: 'Masala & Seasoning', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Oil & Ghee', key: 'Oil & Ghee', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Gourmet & World Foods', key: 'Gourmet & World Foods', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food", imageUrl: Grocery},
        {value: 'Foodgrains', key: 'Foodgrains', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Eggs, Meat & Fish', key: 'Eggs, Meat & Fish', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Cleaning & Household', key: 'Cleaning & Household', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Beverages', key: 'Beverages', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food", imageUrl: Grocery},
        {value: 'Beauty & Hygiene', key: 'Beauty & Hygiene', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Bakery, Cakes & Dairy', key: 'Bakery, Cakes & Dairy', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food", imageUrl: Grocery},
        {value: 'Kitchen Accessories', key: 'Kitchen Accessories', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Baby Care', key: 'Baby Care', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Snacks & Branded Foods', key: 'Snacks & Branded Foods', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food", imageUrl: Grocery},
        {value: 'Pet Care', key: 'Pet Care', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
        {value: 'Stationery', key: 'Stationery', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Grocery},
    ],
    "Beauty & Personal Care": [
        {value: "Bath & Body", key: "Bath & Body", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Feminine Care", key: "Feminine Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Fragrance", key: "Fragrance", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Hair Care", key: "Hair Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Make Up", key: "Make Up", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Men's Grooming", key: "Men's Grooming", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Oral Care", key: "Oral Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Skin Care", key: "Skin Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Maternity Care", key: "Maternity Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Nursing & Feeding", key: "Nursing & Feeding", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Sexual Wellness & Sensuality", key: "Sexual Wellness & Sensuality", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
        {value: "Tools & Accessories", key: "Tools & Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: BPC},
    ],
    "Fashion": [
        {value: "Men's Fashion Accessories", key: "Men's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Footwear Accessories", key: "Men's Footwear Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Topwear", key: "Men's Topwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Bottomwear", key: "Men's Bottomwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Innerwear & Sleepwear", key: "Men's Innerwear & Sleepwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Bags & Luggage", key: "Men's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Eyewear", key: "Men's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Footwear", key: "Men's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Men's Jewellery", key: "Men's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Fashion Accessories", key: "Women's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Footwear Accessories", key: "Women's Footwear Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Indian & Fusion Wear", key: "Women's Indian & Fusion Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Western Wear", key: "Women's Western Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Lingerie & Sleepwear", key: "Women's Lingerie & Sleepwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Bags & Luggage", key: "Women's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Eyewear", key: "Women's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Footwear", key: "Women's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Women's Jewellery", key: "Women's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Boy's Clothing", key: "Boy's Clothing", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Boy's Footwear", key: "Boy's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Girl's Clothing", key: "Girl's Clothing", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Girl's Footwear", key: "Girl's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant's Wear", key: "Infant's Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant Care & Accessories", key: "Infant Care & Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant Feeding & Nursing Essentials", key: "Infant Feeding & Nursing Essentials", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant Bath Accessories", key: "Infant Bath Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant Health & Safety", key: "Infant Health & Safety", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Infant Diapers & Toilet Training", key: "Infant Diapers & Toilet Training", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Kid's Towels & Wrappers", key: "Kid's Towels & Wrappers", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Kid's Fashion Accessories", key: "Kid's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Kid's Jewellery", key: "Kid's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "Kid's Eyewear", key: "Kid's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
        {value: "kids Kid's Bags & Luggage", key: "Kid's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Fashion},
    ],
    "Home & Decor": [
        {value: 'Home Decor', key: 'Home Decor', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Home Furnishings', key: 'Home Furnishings', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Furniture', key: 'Furniture', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Garden and Outdoor Products', key: 'Garden and Outdoor Products', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Home Improvement', key: 'Home Improvement', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Cookware and Dining', key: 'Cookware and Dining', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
        {value: 'Storage and Organisation', key: 'Storage and Organisation', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Home},
    ],
    "F&B": [
        {value: 'Baklava', key: 'Baklava', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Bao', key: 'Bao', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Barbecue', key: 'Barbecue', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Biryani', key: 'Biryani', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Bread', key: 'Bread', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Burger', key: 'Burger', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Cakes', key: 'Cakes', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Chaat', key: 'Chaat', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Cheesecakes', key: 'Cheesecakes', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Chicken', key: 'Chicken', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Chicken wings', key: 'Chicken wings', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Chips', key: 'Chips', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Coffee', key: 'Coffee', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Cookies', key: 'Cookies', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Crepes', key: 'Crepes', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Dal', key: 'Dal', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Desserts', key: 'Desserts', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Dhokla', key: 'Dhokla', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Dosa', key: 'Dosa', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Doughnuts', key: 'Doughnuts', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Eggs', key: 'Eggs', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Energy Drinks', key: 'Energy Drinks', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Falafel', key: 'Falafel', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Fresh Juice', key: 'Fresh Juice', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Fries', key: 'Fries', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Ice cream', key: 'Ice cream', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Idli', key: 'Idli', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Kabab', key: 'Kabab', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Kachori', key: 'Kachori', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Kulfi', key: 'Kulfi', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Lassi', key: 'Lassi', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Meal bowl', key: 'Meal bowl', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Mezze', key: 'Mezze', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Mithai', key: 'Mithai', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Momos', key: 'Momos', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Mutton', key: 'Mutton', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Nachos', key: 'Nachos', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Noodles', key: 'Noodles', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pakodas', key: 'Pakodas', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pancakes', key: 'Pancakes', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Paneer', key: 'Paneer', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pasta', key: 'Pasta', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pastries', key: 'Pastries', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pie', key: 'Pie', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Pizza', key: 'Pizza', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Poha', key: 'Poha', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Raita', key: 'Raita', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Rice', key: 'Rice', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Rolls', key: 'Rolls', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Roti', key: 'Roti', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Salad', key: 'Salad', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Samosa', key: 'Samosa', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Sandwich', key: 'Sandwich', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Seafood', key: 'Seafood', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Shakes & Smoothies', key: 'Shakes & Smoothies', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Soft Drink', key: 'Soft Drink', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Soup', key: 'Soup', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Spring Roll', key: 'Spring Roll', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Sushi', key: 'Sushi', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Tacos', key: 'Tacos', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Tandoori', key: 'Tandoori', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Tart', key: 'Tart', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Tea', key: 'Tea', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Thali', key: 'Thali', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Tikka', key: 'Tikka', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Upma', key: 'Upma', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Uttapam', key: 'Uttapam', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Vada', key: 'Vada', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Vegetables', key: 'Vegetables', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Waffle', key: 'Waffle', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Wrap', key: 'Wrap', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
        {value: 'Yogurt', key: 'Yogurt', protocolKey: '@ondc/org/mandatory_reqs_veggies_fruits', imageUrl: Food},
    ],
    "Electronics": [
        {value: "Audio", key: "Audio", protocolKey: "", imageUrl: Electronics},
        {value: "Camera and Camcorder",key: "Camera and Camcorder", protocolKey: "", imageUrl: Electronics},
        {value: "Computer Peripheral", key: "Computer Peripheral", protocolKey: "", imageUrl: Electronics},
        {value: "Desktop and Laptop", key: "Desktop and Laptop", protocolKey: "", imageUrl: Electronics},
        {value: "Earphone", key: "Earphone", protocolKey: "", imageUrl: Electronics},
        {value: "Gaming", key: "Gaming", protocolKey: "", imageUrl: Electronics},
        {value: "Headphone", key: "Headphone", protocolKey: "", imageUrl: Electronics},
        {value: "Mobile Phone", key: "Mobile Phone", protocolKey: "", imageUrl: Electronics},
        {value: "Mobile Accessories", key: "Mobile Accessories", protocolKey: "", imageUrl: Electronics},
        {value: "Safety Security", key: "Safety Security", protocolKey: "", imageUrl: Electronics},
        {value: "Smart Watches", key: "Smart Watches", protocolKey: "", imageUrl: Electronics},
        {value: "Speaker", key: "Speaker", protocolKey: "", imageUrl: Electronics},
        {value: "Television", key: "Television", protocolKey: "", imageUrl: Electronics},
        {value: "Video", key: "Video", protocolKey: "", imageUrl: Electronics},
        {value: "Air Conditioning and Air Cleaners", key: "Air Conditioning and Air Cleaners", protocolKey: "", imageUrl: Electronics},
        {value: "Health, Home and Personal Care", key: "Health, Home and Personal Care", protocolKey: "", imageUrl: Electronics},
        {value: "Heaters", key: "Heaters", protocolKey: "", imageUrl: Electronics},
        {value: "Kitchen Appliances", key: "Kitchen Appliances", protocolKey: "", imageUrl: Electronics},
        {value: "Lighting & Electric Fans", key: "Lighting & Electric Fans", protocolKey: "", imageUrl: Electronics},
        {value: "Refrigerators and Freezers", key: "Refrigerators and Freezers", protocolKey: "", imageUrl: Electronics},
        {value: "Vacuum Cleaners", key: "Vacuum Cleaners", protocolKey: "", imageUrl: Electronics},
        {value: "Washing Machines and Accessories", key: "Washing Machines and Accessories", protocolKey: "", imageUrl: Electronics},
        {value: "Water Purifiers and Coolers", key: "Water Purifiers and Coolers", protocolKey: "", imageUrl: Electronics},
        {value: "Inverter & Stabilizer", key: "Inverter & Stabilizer", protocolKey: "", imageUrl: Electronics}
    ],
    "Health & Wellness": [
        {key: "Pain Relief", value: "Pain Relief", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Nutrition and Fitness Supplements", value: "Nutrition and Fitness Supplements", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Personal Care", value: "Personal Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Speciality Care", value: "Speciality Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Covid Essentials", value: "Covid Essentials", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Diabetes Control", value: "Diabetes Control", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Healthcare Devices", value: "Healthcare Devices", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
        {key: "Ayush", value: "Ayush", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities", imageUrl: Health},
    ]
};